### ISSUE TITLE
As a user I want to have a suggestion of  a method name in order to know which methods are available

### ISSUE THREAD

**Issue by cwortel** [amolenaar/fitnesse#2]
As a user I want to have a suggestion of  a method name in order to know which methods are available

Create an auto complete function which allows you to:
- choose from available scenario's (in the scenario library)
- choose from available methods from custom fixtures

**Comment by amolenaar** [comment]
Check out https://plugins.jetbrains.com/plugin/7908?pr=. auto-complete will come next.
